name = "cfnew"
main = "index.js"
compatibility_date = "2024-10-01"

[build]
command = "node -e \"const fs = require('fs'); fs.copyFileSync('明文源吗', 'index.js');\""

[[kv_namespaces]]
binding = "C"
id = "2966e383796647828fa8fee443f505a8"

[vars]
u = "c345302c-6343-4bc4-82da-d7ea19c50a95"



